import { Project, Expense, Material, Worker, Attendance } from "./types";

export const mockProjects: Project[] = [
  {
    id: "1",
    name: "Colombo City Centre Tower",
    description: "45-story mixed-use development with retail podium",
    clientName: "Colombo Developers Ltd",
    startDate: "2025-01-15",
    endDate: "2026-08-30",
    status: "active",
    budget: 2500000000,
    totalExpenses: 1850000000,
    progress: 65,
    location: "Colombo 02",
    createdAt: "2025-01-10",
  },
  {
    id: "2",
    name: "Kandy Hills Residences",
    description: "Luxury housing complex with 120 units",
    clientName: "Hill Country Properties",
    startDate: "2025-03-01",
    endDate: "2026-03-15",
    status: "active",
    budget: 850000000,
    totalExpenses: 420000000,
    progress: 45,
    location: "Kandy",
    createdAt: "2025-02-20",
  },
  {
    id: "3",
    name: "Galle Marina Hotel",
    description: "5-star beachfront hotel with 200 rooms",
    clientName: "Southern Hospitality Ltd",
    startDate: "2024-11-01",
    endDate: "2025-12-31",
    status: "on_hold",
    budget: 1800000000,
    totalExpenses: 950000000,
    progress: 55,
    location: "Galle",
    createdAt: "2024-10-15",
  },
  {
    id: "4",
    name: "Jaffna Cultural Centre",
    description: "Community centre with library and theater",
    clientName: "Northern Development Board",
    startDate: "2024-08-01",
    endDate: "2025-06-30",
    status: "completed",
    budget: 450000000,
    totalExpenses: 438000000,
    progress: 100,
    location: "Jaffna",
    createdAt: "2024-07-20",
  },
  {
    id: "5",
    name: "Negombo Waterfront Apartments",
    description: "Waterfront residential development - Phase 1",
    clientName: "Coastal Properties Ltd",
    startDate: "2025-06-01",
    endDate: "2027-01-31",
    status: "planning",
    budget: 1200000000,
    totalExpenses: 45000000,
    progress: 5,
    location: "Negombo",
    createdAt: "2025-05-15",
  },
];

export const mockExpenses: Expense[] = [
  {
    id: "1",
    projectId: "1",
    category: "materials",
    amount: 750000,
    description: "Steel reinforcement bars",
    date: "2025-11-15",
  },
  {
    id: "2",
    projectId: "1",
    category: "labor",
    amount: 450000,
    description: "November wages - Floor 15-20",
    date: "2025-11-14",
  },
  {
    id: "3",
    projectId: "1",
    category: "equipment",
    amount: 320000,
    description: "Crane rental - Monthly",
    date: "2025-11-13",
  },
  {
    id: "4",
    projectId: "1",
    category: "subcontractor",
    amount: 890000,
    description: "Electrical work - Floor 10-15",
    date: "2025-11-12",
  },
  {
    id: "5",
    projectId: "1",
    category: "materials",
    amount: 520000,
    description: "Cement - 500 bags",
    date: "2025-11-10",
  },
  {
    id: "6",
    projectId: "2",
    category: "permits",
    amount: 150000,
    description: "Building permit renewal",
    date: "2025-11-14",
  },
  {
    id: "7",
    projectId: "2",
    category: "materials",
    amount: 680000,
    description: "Tiles and sanitaryware",
    date: "2025-11-13",
  },
];

export const mockMaterials: Material[] = [
  {
    id: "1",
    projectId: "1",
    name: "Cement",
    unit: "bags",
    quantityOrdered: 5000,
    quantityUsed: 3200,
    unitCost: 1450,
    supplier: "Tokyo Cement",
  },
  {
    id: "2",
    projectId: "1",
    name: "Steel Rebar",
    unit: "tons",
    quantityOrdered: 200,
    quantityUsed: 145,
    unitCost: 285000,
    supplier: "Ceylon Steel",
  },
  {
    id: "3",
    projectId: "1",
    name: "Sand",
    unit: "cubes",
    quantityOrdered: 800,
    quantityUsed: 520,
    unitCost: 12500,
    supplier: "Dedicated Supplier",
  },
  {
    id: "4",
    projectId: "2",
    name: "Bricks",
    unit: "pieces",
    quantityOrdered: 100000,
    quantityUsed: 45000,
    unitCost: 35,
    supplier: "Local Brickworks",
  },
  {
    id: "5",
    projectId: "1",
    name: "Gravel",
    unit: "cubes",
    quantityOrdered: 300,
    quantityUsed: 180,
    unitCost: 8500,
    supplier: "Quarry Ltd",
  },
  {
    id: "6",
    projectId: "2",
    name: "Cement",
    unit: "bags",
    quantityOrdered: 2000,
    quantityUsed: 800,
    unitCost: 1450,
    supplier: "Tokyo Cement",
  },
  {
    id: "7",
    projectId: "2",
    name: "Tiles",
    unit: "sqm",
    quantityOrdered: 5000,
    quantityUsed: 1200,
    unitCost: 2200,
    supplier: "Lanka Tiles",
  },
  {
    id: "8",
    projectId: "2",
    name: "PVC Pipes",
    unit: "meters",
    quantityOrdered: 2000,
    quantityUsed: 900,
    unitCost: 450,
    supplier: "National Plastics",
  },
];

export const mockWorkers: Worker[] = [
  {
    id: "1",
    projectId: "1",
    fullName: "Saman Kumara",
    role: "Mason",
    dailyWage: 3500,
    phone: "0771234567",
  },
  {
    id: "2",
    projectId: "1",
    fullName: "Priyantha Silva",
    role: "Carpenter",
    dailyWage: 4000,
    phone: "0772345678",
  },
  {
    id: "3",
    projectId: "1",
    fullName: "Nimal Perera",
    role: "Laborer",
    dailyWage: 2500,
    phone: "0773456789",
  },
  {
    id: "4",
    projectId: "1",
    fullName: "Sunil Bandara",
    role: "Electrician",
    dailyWage: 4500,
    phone: "0774567890",
  },
  {
    id: "5",
    projectId: "1",
    fullName: "Kamal Fernando",
    role: "Plumber",
    dailyWage: 4200,
    phone: "0775678901",
  },
  {
    id: "6",
    projectId: "2",
    fullName: "Rohan Wickramasinghe",
    role: "Mason",
    dailyWage: 3500,
    phone: "0776789012",
  },
  {
    id: "7",
    projectId: "2",
    fullName: "Nuwan Jayawardena",
    role: "Laborer",
    dailyWage: 2500,
    phone: "0777890123",
  },
];

export const mockAttendance: Attendance[] = [
  {
    id: "1",
    workerId: "1",
    workerName: "Saman Kumara",
    projectId: "1",
    date: "2025-11-15",
    status: "present",
    hoursWorked: 8,
  },
  {
    id: "2",
    workerId: "2",
    workerName: "Priyantha Silva",
    projectId: "1",
    date: "2025-11-15",
    status: "present",
    hoursWorked: 9,
  },
  {
    id: "3",
    workerId: "3",
    workerName: "Nimal Perera",
    projectId: "1",
    date: "2025-11-15",
    status: "absent",
    hoursWorked: 0,
  },
  {
    id: "4",
    workerId: "4",
    workerName: "Sunil Bandara",
    projectId: "1",
    date: "2025-11-15",
    status: "half_day",
    hoursWorked: 4,
  },
  {
    id: "5",
    workerId: "5",
    workerName: "Kamal Fernando",
    projectId: "1",
    date: "2025-11-15",
    status: "overtime",
    hoursWorked: 10,
  },
  // More days for project 1
  {
    id: "6",
    workerId: "1",
    workerName: "Saman Kumara",
    projectId: "1",
    date: "2025-11-14",
    status: "present",
    hoursWorked: 8,
  },
  {
    id: "7",
    workerId: "2",
    workerName: "Priyantha Silva",
    projectId: "1",
    date: "2025-11-14",
    status: "present",
    hoursWorked: 8,
  },
  {
    id: "8",
    workerId: "3",
    workerName: "Nimal Perera",
    projectId: "1",
    date: "2025-11-14",
    status: "present",
    hoursWorked: 8,
  },
  {
    id: "9",
    workerId: "4",
    workerName: "Sunil Bandara",
    projectId: "1",
    date: "2025-11-14",
    status: "absent",
    hoursWorked: 0,
  },
  {
    id: "10",
    workerId: "5",
    workerName: "Kamal Fernando",
    projectId: "1",
    date: "2025-11-14",
    status: "present",
    hoursWorked: 8,
  },
];

// Monthly expense data for charts
export const monthlyExpenses = [
  { month: "Jan", materials: 45, labor: 32, equipment: 18, subcontractor: 25 },
  { month: "Feb", materials: 52, labor: 35, equipment: 20, subcontractor: 28 },
  { month: "Mar", materials: 48, labor: 38, equipment: 22, subcontractor: 30 },
  { month: "Apr", materials: 61, labor: 42, equipment: 25, subcontractor: 35 },
  { month: "May", materials: 55, labor: 40, equipment: 28, subcontractor: 32 },
  { month: "Jun", materials: 67, labor: 45, equipment: 30, subcontractor: 38 },
  { month: "Jul", materials: 72, labor: 48, equipment: 32, subcontractor: 42 },
  { month: "Aug", materials: 58, labor: 44, equipment: 26, subcontractor: 36 },
  { month: "Sep", materials: 63, labor: 46, equipment: 29, subcontractor: 40 },
  { month: "Oct", materials: 70, labor: 50, equipment: 33, subcontractor: 44 },
  { month: "Nov", materials: 78, labor: 52, equipment: 35, subcontractor: 48 },
  { month: "Dec", materials: 0, labor: 0, equipment: 0, subcontractor: 0 },
];

export const budgetBreakdown = [
  { name: "Materials", value: 45, color: "#F97316" },
  { name: "Labor", value: 30, color: "#3B82F6" },
  { name: "Equipment", value: 15, color: "#8B5CF6" },
  { name: "Subcontractor", value: 10, color: "#EC4899" },
];

export const projectProgressData = [
  { name: "Colombo CC", progress: 65, budget: 2500, spent: 1850 },
  { name: "Kandy Hills", progress: 45, budget: 850, spent: 420 },
  { name: "Galle Marina", progress: 55, budget: 1800, spent: 950 },
  { name: "Jaffna CC", progress: 100, budget: 450, spent: 438 },
  { name: "Negombo WF", progress: 5, budget: 1200, spent: 45 },
];
